/**
 * QuantiModo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH }                                         from '../variables';
import { Configuration }                                     from '../configuration';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class CorrelationsApi {
    protected basePath = 'https://app.quantimo.do/api';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }
	
	/**
     * 
     * Extends object by coping non-existing properties.
     * @param objA object to be extended
     * @param objB source object
     */
    private extendObj<T1,T2>(objA: T1, objB: T2) {
        for(let key in objB){
            if(objB.hasOwnProperty(key)){
                objA[key] = objB[key];
            }
        }
        return <T1&T2>objA;
    }

    /**
     * Get aggregated correlations
     * Get correlations based on the anonymized aggregate data from all QuantiModo users.
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     * @param effect Variable name of the effect variable for which the user desires correlations
     * @param cause Variable name of the cause variable for which the user desires correlations
     * @param correlationCoefficient Pearson correlation coefficient between cause and effect after lagging by onset delay and grouping by duration of action
     * @param onsetDelay The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes.
     * @param durationOfAction The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.
     * @param updatedAt The time that this measurement was last updated in the UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot;.  Generally, you&#39;ll be retrieving new or updated user data. To avoid unnecessary API calls, you&#39;ll want to store your last refresh time locally. Then whenever you make a request to get new data, you should limit the returned results to those updated since your last refresh by appending append &#x60;?updatedAt&#x3D;(ge)2013-01-D01T01:01:01 to your request.
     * @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0.
     * @param offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;.
     * @param sort Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order.
     * @param outcomesOfInterest Only include correlations for which the effect is an outcome of interest for the user
     */
    public v1AggregatedCorrelationsGet(accessToken?: string, userId?: number, effect?: string, cause?: string, correlationCoefficient?: string, onsetDelay?: string, durationOfAction?: string, updatedAt?: string, limit?: number, offset?: number, sort?: number, outcomesOfInterest?: boolean, extraHttpRequestParams?: any): Observable<Array<models.Correlation>> {
        return this.v1AggregatedCorrelationsGetWithHttpInfo(accessToken, userId, effect, cause, correlationCoefficient, onsetDelay, durationOfAction, updatedAt, limit, offset, sort, outcomesOfInterest, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Store or Update a Correlation
     * Add correlation
     * @param body Provides correlation data
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     */
    public v1AggregatedCorrelationsPost(body: models.PostCorrelation, accessToken?: string, userId?: number, extraHttpRequestParams?: any): Observable<{}> {
        return this.v1AggregatedCorrelationsPostWithHttpInfo(body, accessToken, userId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Get correlations
     * Get correlations based on data from a single user.
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     * @param effect Variable name of the effect variable for which the user desires correlations
     * @param cause Variable name of the cause variable for which the user desires correlations
     * @param correlationCoefficient Pearson correlation coefficient between cause and effect after lagging by onset delay and grouping by duration of action
     * @param onsetDelay The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes.
     * @param durationOfAction The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.
     * @param updatedAt The time that this measurement was last updated in the UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot;.  Generally, you&#39;ll be retrieving new or updated user data. To avoid unnecessary API calls, you&#39;ll want to store your last refresh time locally. Then whenever you make a request to get new data, you should limit the returned results to those updated since your last refresh by appending append &#x60;?updatedAt&#x3D;(ge)2013-01-D01T01:01:01 to your request.
     * @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0.
     * @param offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;.
     * @param sort Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order.
     * @param outcomesOfInterest Only include correlations for which the effect is an outcome of interest for the user
     */
    public v1CorrelationsGet(accessToken?: string, userId?: number, effect?: string, cause?: string, correlationCoefficient?: string, onsetDelay?: string, durationOfAction?: string, updatedAt?: string, limit?: number, offset?: number, sort?: number, outcomesOfInterest?: boolean, extraHttpRequestParams?: any): Observable<Array<models.Correlation>> {
        return this.v1CorrelationsGetWithHttpInfo(accessToken, userId, effect, cause, correlationCoefficient, onsetDelay, durationOfAction, updatedAt, limit, offset, sort, outcomesOfInterest, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Search user correlations for a given cause
     * Returns average of all correlations and votes for all user cause variables for a given cause. If parameter \&quot;include_public\&quot; is used, it also returns public correlations. User correlation overwrites or supersedes public correlation.
     * @param organizationId Organization ID
     * @param userId2 User id
     * @param variableName Effect variable name
     * @param organizationToken Organization access token
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     * @param includePublic Include public correlations, Can be \&quot;1\&quot; or empty.
     */
    public v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameCausesGet(organizationId: number, userId2: number, variableName: string, organizationToken: string, accessToken?: string, userId?: number, includePublic?: string, extraHttpRequestParams?: any): Observable<Array<models.Correlation>> {
        return this.v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameCausesGetWithHttpInfo(organizationId, userId2, variableName, organizationToken, accessToken, userId, includePublic, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Search user correlations for a given cause
     * Returns average of all correlations and votes for all user cause variables for a given effect. If parameter \&quot;include_public\&quot; is used, it also returns public correlations. User correlation overwrites or supersedes public correlation.
     * @param organizationId Organization ID
     * @param userId2 User id
     * @param variableName Cause variable name
     * @param organizationToken Organization access token
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     * @param includePublic Include public correlations, Can be \&quot;1\&quot; or empty.
     */
    public v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameEffectsGet(organizationId: number, userId2: number, variableName: string, organizationToken: string, accessToken?: string, userId?: number, includePublic?: string, extraHttpRequestParams?: any): Observable<Array<models.CommonResponse>> {
        return this.v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameEffectsGetWithHttpInfo(organizationId, userId2, variableName, organizationToken, accessToken, userId, includePublic, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Get average correlations for variables containing search term
     * Returns the average correlations from all users for all public variables that contain the characters in the search query. Returns average of all users public variable correlations with a specified cause or effect.
     * @param search Name of the variable that you want to know the causes or effects of.
     * @param effectOrCause Setting this to effect indicates that the searched variable is the effect and that the causes of this variable should be returned. cause indicates that the searched variable is the cause and the effects should be returned.
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     * @param outcomesOfInterest Only include correlations for which the effect is an outcome of interest for the user
     */
    public v1PublicCorrelationsSearchSearchGet(search: string, effectOrCause: string, accessToken?: string, userId?: number, outcomesOfInterest?: boolean, extraHttpRequestParams?: any): Observable<Array<models.Correlation>> {
        return this.v1PublicCorrelationsSearchSearchGetWithHttpInfo(search, effectOrCause, accessToken, userId, outcomesOfInterest, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Search user correlations for a given effect
     * Returns average of all correlations and votes for all user cause variables for a given effect
     * @param variableName Effect variable name
     */
    public v1VariablesVariableNameCausesGet(variableName: string, extraHttpRequestParams?: any): Observable<Array<models.Correlation>> {
        return this.v1VariablesVariableNameCausesGetWithHttpInfo(variableName, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Search user correlations for a given cause
     * Returns average of all correlations and votes for all user effect variables for a given cause
     * @param variableName Cause variable name
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     * @param correlationCoefficient You can use this to get effects with correlations greater than or less than 0
     */
    public v1VariablesVariableNameEffectsGet(variableName: string, accessToken?: string, userId?: number, correlationCoefficient?: string, extraHttpRequestParams?: any): Observable<Array<models.Correlation>> {
        return this.v1VariablesVariableNameEffectsGetWithHttpInfo(variableName, accessToken, userId, correlationCoefficient, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Search public correlations for a given effect
     * Returns average of all correlations and votes for all public cause variables for a given effect
     * @param variableName Effect variable name
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     * @param correlationCoefficient You can use this to get causes with correlations greater than or less than 0
     */
    public v1VariablesVariableNamePublicCausesGet(variableName: string, accessToken?: string, userId?: number, correlationCoefficient?: string, extraHttpRequestParams?: any): Observable<Array<models.Correlation>> {
        return this.v1VariablesVariableNamePublicCausesGetWithHttpInfo(variableName, accessToken, userId, correlationCoefficient, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Search public correlations for a given cause
     * Returns average of all correlations and votes for all public cause variables for a given cause
     * @param variableName Cause variable name
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     */
    public v1VariablesVariableNamePublicEffectsGet(variableName: string, accessToken?: string, userId?: number, extraHttpRequestParams?: any): Observable<Array<models.Correlation>> {
        return this.v1VariablesVariableNamePublicEffectsGetWithHttpInfo(variableName, accessToken, userId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Delete vote
     * Delete previously posted vote
     * @param body The cause and effect variable names for the predictor vote to be deleted.
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     */
    public v1VotesDeletePost(body: models.VoteDelete, accessToken?: string, userId?: number, extraHttpRequestParams?: any): Observable<models.CommonResponse> {
        return this.v1VotesDeletePostWithHttpInfo(body, accessToken, userId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Post or update vote
     * This is to enable users to indicate their opinion on the plausibility of a causal relationship between a treatment and outcome. QuantiModo incorporates crowd-sourced plausibility estimations into their algorithm. This is done allowing user to indicate their view of the plausibility of each relationship with thumbs up/down buttons placed next to each prediction.
     * @param body Contains the cause variable, effect variable, and vote value.
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     */
    public v1VotesPost(body: models.PostVote, accessToken?: string, userId?: number, extraHttpRequestParams?: any): Observable<models.CommonResponse> {
        return this.v1VotesPostWithHttpInfo(body, accessToken, userId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }


    /**
     * Get aggregated correlations
     * Get correlations based on the anonymized aggregate data from all QuantiModo users.
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     * @param effect Variable name of the effect variable for which the user desires correlations
     * @param cause Variable name of the cause variable for which the user desires correlations
     * @param correlationCoefficient Pearson correlation coefficient between cause and effect after lagging by onset delay and grouping by duration of action
     * @param onsetDelay The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes.
     * @param durationOfAction The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.
     * @param updatedAt The time that this measurement was last updated in the UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot;.  Generally, you&#39;ll be retrieving new or updated user data. To avoid unnecessary API calls, you&#39;ll want to store your last refresh time locally. Then whenever you make a request to get new data, you should limit the returned results to those updated since your last refresh by appending append &#x60;?updatedAt&#x3D;(ge)2013-01-D01T01:01:01 to your request.
     * @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0.
     * @param offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;.
     * @param sort Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order.
     * @param outcomesOfInterest Only include correlations for which the effect is an outcome of interest for the user
     */
    public v1AggregatedCorrelationsGetWithHttpInfo(accessToken?: string, userId?: number, effect?: string, cause?: string, correlationCoefficient?: string, onsetDelay?: string, durationOfAction?: string, updatedAt?: string, limit?: number, offset?: number, sort?: number, outcomesOfInterest?: boolean, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v1/aggregatedCorrelations`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        if (accessToken !== undefined) {
            queryParameters.set('access_token', <any>accessToken);
        }
        if (userId !== undefined) {
            queryParameters.set('userId', <any>userId);
        }
        if (effect !== undefined) {
            queryParameters.set('effect', <any>effect);
        }
        if (cause !== undefined) {
            queryParameters.set('cause', <any>cause);
        }
        if (correlationCoefficient !== undefined) {
            queryParameters.set('correlationCoefficient', <any>correlationCoefficient);
        }
        if (onsetDelay !== undefined) {
            queryParameters.set('onsetDelay', <any>onsetDelay);
        }
        if (durationOfAction !== undefined) {
            queryParameters.set('durationOfAction', <any>durationOfAction);
        }
        if (updatedAt !== undefined) {
            queryParameters.set('updatedAt', <any>updatedAt);
        }
        if (limit !== undefined) {
            queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined) {
            queryParameters.set('offset', <any>offset);
        }
        if (sort !== undefined) {
            queryParameters.set('sort', <any>sort);
        }
        if (outcomesOfInterest !== undefined) {
            queryParameters.set('outcomesOfInterest', <any>outcomesOfInterest);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (access_token) required
        if (this.configuration.apiKey)
        {
            formParams.set('access_token', this.configuration.apiKey);
        }
        // authentication (quantimodo_oauth2) required
        // oauth required
        if (this.configuration.accessToken)
        {
            headers.set('Authorization', 'Bearer ' + this.configuration.accessToken);
        }
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Store or Update a Correlation
     * Add correlation
     * @param body Provides correlation data
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     */
    public v1AggregatedCorrelationsPostWithHttpInfo(body: models.PostCorrelation, accessToken?: string, userId?: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v1/aggregatedCorrelations`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'body' is not null or undefined
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling v1AggregatedCorrelationsPost.');
        }
        if (accessToken !== undefined) {
            queryParameters.set('access_token', <any>accessToken);
        }
        if (userId !== undefined) {
            queryParameters.set('userId', <any>userId);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (access_token) required
        if (this.configuration.apiKey)
        {
            formParams.set('access_token', this.configuration.apiKey);
        }
        // authentication (quantimodo_oauth2) required
        // oauth required
        if (this.configuration.accessToken)
        {
            headers.set('Authorization', 'Bearer ' + this.configuration.accessToken);
        }
            

        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Get correlations
     * Get correlations based on data from a single user.
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     * @param effect Variable name of the effect variable for which the user desires correlations
     * @param cause Variable name of the cause variable for which the user desires correlations
     * @param correlationCoefficient Pearson correlation coefficient between cause and effect after lagging by onset delay and grouping by duration of action
     * @param onsetDelay The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes.
     * @param durationOfAction The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.
     * @param updatedAt The time that this measurement was last updated in the UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot;.  Generally, you&#39;ll be retrieving new or updated user data. To avoid unnecessary API calls, you&#39;ll want to store your last refresh time locally. Then whenever you make a request to get new data, you should limit the returned results to those updated since your last refresh by appending append &#x60;?updatedAt&#x3D;(ge)2013-01-D01T01:01:01 to your request.
     * @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0.
     * @param offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;.
     * @param sort Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order.
     * @param outcomesOfInterest Only include correlations for which the effect is an outcome of interest for the user
     */
    public v1CorrelationsGetWithHttpInfo(accessToken?: string, userId?: number, effect?: string, cause?: string, correlationCoefficient?: string, onsetDelay?: string, durationOfAction?: string, updatedAt?: string, limit?: number, offset?: number, sort?: number, outcomesOfInterest?: boolean, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v1/correlations`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        if (accessToken !== undefined) {
            queryParameters.set('access_token', <any>accessToken);
        }
        if (userId !== undefined) {
            queryParameters.set('userId', <any>userId);
        }
        if (effect !== undefined) {
            queryParameters.set('effect', <any>effect);
        }
        if (cause !== undefined) {
            queryParameters.set('cause', <any>cause);
        }
        if (correlationCoefficient !== undefined) {
            queryParameters.set('correlationCoefficient', <any>correlationCoefficient);
        }
        if (onsetDelay !== undefined) {
            queryParameters.set('onsetDelay', <any>onsetDelay);
        }
        if (durationOfAction !== undefined) {
            queryParameters.set('durationOfAction', <any>durationOfAction);
        }
        if (updatedAt !== undefined) {
            queryParameters.set('updatedAt', <any>updatedAt);
        }
        if (limit !== undefined) {
            queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined) {
            queryParameters.set('offset', <any>offset);
        }
        if (sort !== undefined) {
            queryParameters.set('sort', <any>sort);
        }
        if (outcomesOfInterest !== undefined) {
            queryParameters.set('outcomesOfInterest', <any>outcomesOfInterest);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (access_token) required
        if (this.configuration.apiKey)
        {
            formParams.set('access_token', this.configuration.apiKey);
        }
        // authentication (quantimodo_oauth2) required
        // oauth required
        if (this.configuration.accessToken)
        {
            headers.set('Authorization', 'Bearer ' + this.configuration.accessToken);
        }
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Search user correlations for a given cause
     * Returns average of all correlations and votes for all user cause variables for a given cause. If parameter \&quot;include_public\&quot; is used, it also returns public correlations. User correlation overwrites or supersedes public correlation.
     * @param organizationId Organization ID
     * @param userId2 User id
     * @param variableName Effect variable name
     * @param organizationToken Organization access token
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     * @param includePublic Include public correlations, Can be \&quot;1\&quot; or empty.
     */
    public v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameCausesGetWithHttpInfo(organizationId: number, userId2: number, variableName: string, organizationToken: string, accessToken?: string, userId?: number, includePublic?: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v1/organizations/${organizationId}/users/${userId}/variables/${variableName}/causes`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'organizationId' is not null or undefined
        if (organizationId === null || organizationId === undefined) {
            throw new Error('Required parameter organizationId was null or undefined when calling v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameCausesGet.');
        }
        // verify required parameter 'userId2' is not null or undefined
        if (userId2 === null || userId2 === undefined) {
            throw new Error('Required parameter userId2 was null or undefined when calling v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameCausesGet.');
        }
        // verify required parameter 'variableName' is not null or undefined
        if (variableName === null || variableName === undefined) {
            throw new Error('Required parameter variableName was null or undefined when calling v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameCausesGet.');
        }
        // verify required parameter 'organizationToken' is not null or undefined
        if (organizationToken === null || organizationToken === undefined) {
            throw new Error('Required parameter organizationToken was null or undefined when calling v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameCausesGet.');
        }
        if (accessToken !== undefined) {
            queryParameters.set('access_token', <any>accessToken);
        }
        if (userId !== undefined) {
            queryParameters.set('userId', <any>userId);
        }
        if (organizationToken !== undefined) {
            queryParameters.set('organization_token', <any>organizationToken);
        }
        if (includePublic !== undefined) {
            queryParameters.set('includePublic', <any>includePublic);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (access_token) required
        if (this.configuration.apiKey)
        {
            formParams.set('access_token', this.configuration.apiKey);
        }
        // authentication (quantimodo_oauth2) required
        // oauth required
        if (this.configuration.accessToken)
        {
            headers.set('Authorization', 'Bearer ' + this.configuration.accessToken);
        }
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Search user correlations for a given cause
     * Returns average of all correlations and votes for all user cause variables for a given effect. If parameter \&quot;include_public\&quot; is used, it also returns public correlations. User correlation overwrites or supersedes public correlation.
     * @param organizationId Organization ID
     * @param userId2 User id
     * @param variableName Cause variable name
     * @param organizationToken Organization access token
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     * @param includePublic Include public correlations, Can be \&quot;1\&quot; or empty.
     */
    public v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameEffectsGetWithHttpInfo(organizationId: number, userId2: number, variableName: string, organizationToken: string, accessToken?: string, userId?: number, includePublic?: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v1/organizations/${organizationId}/users/${userId}/variables/${variableName}/effects`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'organizationId' is not null or undefined
        if (organizationId === null || organizationId === undefined) {
            throw new Error('Required parameter organizationId was null or undefined when calling v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameEffectsGet.');
        }
        // verify required parameter 'userId2' is not null or undefined
        if (userId2 === null || userId2 === undefined) {
            throw new Error('Required parameter userId2 was null or undefined when calling v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameEffectsGet.');
        }
        // verify required parameter 'variableName' is not null or undefined
        if (variableName === null || variableName === undefined) {
            throw new Error('Required parameter variableName was null or undefined when calling v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameEffectsGet.');
        }
        // verify required parameter 'organizationToken' is not null or undefined
        if (organizationToken === null || organizationToken === undefined) {
            throw new Error('Required parameter organizationToken was null or undefined when calling v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameEffectsGet.');
        }
        if (accessToken !== undefined) {
            queryParameters.set('access_token', <any>accessToken);
        }
        if (userId !== undefined) {
            queryParameters.set('userId', <any>userId);
        }
        if (organizationToken !== undefined) {
            queryParameters.set('organization_token', <any>organizationToken);
        }
        if (includePublic !== undefined) {
            queryParameters.set('include_public', <any>includePublic);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (access_token) required
        if (this.configuration.apiKey)
        {
            formParams.set('access_token', this.configuration.apiKey);
        }
        // authentication (quantimodo_oauth2) required
        // oauth required
        if (this.configuration.accessToken)
        {
            headers.set('Authorization', 'Bearer ' + this.configuration.accessToken);
        }
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Get average correlations for variables containing search term
     * Returns the average correlations from all users for all public variables that contain the characters in the search query. Returns average of all users public variable correlations with a specified cause or effect.
     * @param search Name of the variable that you want to know the causes or effects of.
     * @param effectOrCause Setting this to effect indicates that the searched variable is the effect and that the causes of this variable should be returned. cause indicates that the searched variable is the cause and the effects should be returned.
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     * @param outcomesOfInterest Only include correlations for which the effect is an outcome of interest for the user
     */
    public v1PublicCorrelationsSearchSearchGetWithHttpInfo(search: string, effectOrCause: string, accessToken?: string, userId?: number, outcomesOfInterest?: boolean, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v1/public/correlations/search/${search}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'search' is not null or undefined
        if (search === null || search === undefined) {
            throw new Error('Required parameter search was null or undefined when calling v1PublicCorrelationsSearchSearchGet.');
        }
        // verify required parameter 'effectOrCause' is not null or undefined
        if (effectOrCause === null || effectOrCause === undefined) {
            throw new Error('Required parameter effectOrCause was null or undefined when calling v1PublicCorrelationsSearchSearchGet.');
        }
        if (accessToken !== undefined) {
            queryParameters.set('access_token', <any>accessToken);
        }
        if (userId !== undefined) {
            queryParameters.set('userId', <any>userId);
        }
        if (effectOrCause !== undefined) {
            queryParameters.set('effectOrCause', <any>effectOrCause);
        }
        if (outcomesOfInterest !== undefined) {
            queryParameters.set('outcomesOfInterest', <any>outcomesOfInterest);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (access_token) required
        if (this.configuration.apiKey)
        {
            formParams.set('access_token', this.configuration.apiKey);
        }
        // authentication (quantimodo_oauth2) required
        // oauth required
        if (this.configuration.accessToken)
        {
            headers.set('Authorization', 'Bearer ' + this.configuration.accessToken);
        }
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Search user correlations for a given effect
     * Returns average of all correlations and votes for all user cause variables for a given effect
     * @param variableName Effect variable name
     */
    public v1VariablesVariableNameCausesGetWithHttpInfo(variableName: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v1/variables/${variableName}/causes`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'variableName' is not null or undefined
        if (variableName === null || variableName === undefined) {
            throw new Error('Required parameter variableName was null or undefined when calling v1VariablesVariableNameCausesGet.');
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (access_token) required
        if (this.configuration.apiKey)
        {
            formParams.set('access_token', this.configuration.apiKey);
        }
        // authentication (quantimodo_oauth2) required
        // oauth required
        if (this.configuration.accessToken)
        {
            headers.set('Authorization', 'Bearer ' + this.configuration.accessToken);
        }
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Search user correlations for a given cause
     * Returns average of all correlations and votes for all user effect variables for a given cause
     * @param variableName Cause variable name
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     * @param correlationCoefficient You can use this to get effects with correlations greater than or less than 0
     */
    public v1VariablesVariableNameEffectsGetWithHttpInfo(variableName: string, accessToken?: string, userId?: number, correlationCoefficient?: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v1/variables/${variableName}/effects`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'variableName' is not null or undefined
        if (variableName === null || variableName === undefined) {
            throw new Error('Required parameter variableName was null or undefined when calling v1VariablesVariableNameEffectsGet.');
        }
        if (accessToken !== undefined) {
            queryParameters.set('access_token', <any>accessToken);
        }
        if (userId !== undefined) {
            queryParameters.set('userId', <any>userId);
        }
        if (correlationCoefficient !== undefined) {
            queryParameters.set('correlationCoefficient', <any>correlationCoefficient);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (access_token) required
        if (this.configuration.apiKey)
        {
            formParams.set('access_token', this.configuration.apiKey);
        }
        // authentication (quantimodo_oauth2) required
        // oauth required
        if (this.configuration.accessToken)
        {
            headers.set('Authorization', 'Bearer ' + this.configuration.accessToken);
        }
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Search public correlations for a given effect
     * Returns average of all correlations and votes for all public cause variables for a given effect
     * @param variableName Effect variable name
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     * @param correlationCoefficient You can use this to get causes with correlations greater than or less than 0
     */
    public v1VariablesVariableNamePublicCausesGetWithHttpInfo(variableName: string, accessToken?: string, userId?: number, correlationCoefficient?: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v1/variables/${variableName}/public/causes`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'variableName' is not null or undefined
        if (variableName === null || variableName === undefined) {
            throw new Error('Required parameter variableName was null or undefined when calling v1VariablesVariableNamePublicCausesGet.');
        }
        if (accessToken !== undefined) {
            queryParameters.set('access_token', <any>accessToken);
        }
        if (userId !== undefined) {
            queryParameters.set('userId', <any>userId);
        }
        if (correlationCoefficient !== undefined) {
            queryParameters.set('correlationCoefficient', <any>correlationCoefficient);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (access_token) required
        if (this.configuration.apiKey)
        {
            formParams.set('access_token', this.configuration.apiKey);
        }
        // authentication (quantimodo_oauth2) required
        // oauth required
        if (this.configuration.accessToken)
        {
            headers.set('Authorization', 'Bearer ' + this.configuration.accessToken);
        }
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Search public correlations for a given cause
     * Returns average of all correlations and votes for all public cause variables for a given cause
     * @param variableName Cause variable name
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     */
    public v1VariablesVariableNamePublicEffectsGetWithHttpInfo(variableName: string, accessToken?: string, userId?: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v1/variables/${variableName}/public/effects`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'variableName' is not null or undefined
        if (variableName === null || variableName === undefined) {
            throw new Error('Required parameter variableName was null or undefined when calling v1VariablesVariableNamePublicEffectsGet.');
        }
        if (accessToken !== undefined) {
            queryParameters.set('access_token', <any>accessToken);
        }
        if (userId !== undefined) {
            queryParameters.set('userId', <any>userId);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (access_token) required
        if (this.configuration.apiKey)
        {
            formParams.set('access_token', this.configuration.apiKey);
        }
        // authentication (quantimodo_oauth2) required
        // oauth required
        if (this.configuration.accessToken)
        {
            headers.set('Authorization', 'Bearer ' + this.configuration.accessToken);
        }
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Delete vote
     * Delete previously posted vote
     * @param body The cause and effect variable names for the predictor vote to be deleted.
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     */
    public v1VotesDeletePostWithHttpInfo(body: models.VoteDelete, accessToken?: string, userId?: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v1/votes/delete`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'body' is not null or undefined
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling v1VotesDeletePost.');
        }
        if (accessToken !== undefined) {
            queryParameters.set('access_token', <any>accessToken);
        }
        if (userId !== undefined) {
            queryParameters.set('userId', <any>userId);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (access_token) required
        if (this.configuration.apiKey)
        {
            formParams.set('access_token', this.configuration.apiKey);
        }
        // authentication (quantimodo_oauth2) required
        // oauth required
        if (this.configuration.accessToken)
        {
            headers.set('Authorization', 'Bearer ' + this.configuration.accessToken);
        }
            

        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Post or update vote
     * This is to enable users to indicate their opinion on the plausibility of a causal relationship between a treatment and outcome. QuantiModo incorporates crowd-sourced plausibility estimations into their algorithm. This is done allowing user to indicate their view of the plausibility of each relationship with thumbs up/down buttons placed next to each prediction.
     * @param body Contains the cause variable, effect variable, and vote value.
     * @param accessToken User&#39;s OAuth2 access token
     * @param userId User&#39;s id
     */
    public v1VotesPostWithHttpInfo(body: models.PostVote, accessToken?: string, userId?: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/v1/votes`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'body' is not null or undefined
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling v1VotesPost.');
        }
        if (accessToken !== undefined) {
            queryParameters.set('access_token', <any>accessToken);
        }
        if (userId !== undefined) {
            queryParameters.set('userId', <any>userId);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (access_token) required
        if (this.configuration.apiKey)
        {
            formParams.set('access_token', this.configuration.apiKey);
        }
        // authentication (quantimodo_oauth2) required
        // oauth required
        if (this.configuration.accessToken)
        {
            headers.set('Authorization', 'Bearer ' + this.configuration.accessToken);
        }
            

        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
