export * from './AnalyticsApi';
import { AnalyticsApi } from './AnalyticsApi';
export * from './AuthenticationApi';
import { AuthenticationApi } from './AuthenticationApi';
export * from './ConnectorsApi';
import { ConnectorsApi } from './ConnectorsApi';
export * from './MeasurementsApi';
import { MeasurementsApi } from './MeasurementsApi';
export * from './RemindersApi';
import { RemindersApi } from './RemindersApi';
export * from './UnitsApi';
import { UnitsApi } from './UnitsApi';
export * from './UserApi';
import { UserApi } from './UserApi';
export * from './VariablesApi';
import { VariablesApi } from './VariablesApi';
export const APIS = [AnalyticsApi, AuthenticationApi, ConnectorsApi, MeasurementsApi, RemindersApi, UnitsApi, UserApi, VariablesApi];
