/**
 * quantimodo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.728
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Connector {
    /**
     * Connector ID number
     */
    id: number;

    /**
     * Connector lowercase system name
     */
    name: string;

    /**
     * Connector pretty display name
     */
    displayName: string;

    /**
     * URL to the image of the connector logo
     */
    image: string;

    /**
     * URL to a site where one can get this device or application
     */
    getItUrl: string;

    /**
     * True if the authenticated user has this connector enabled
     */
    connected: string;

    /**
     * URL and parameters used when connecting to a service
     */
    connectInstructions: string;

    /**
     * Epoch timestamp of last sync
     */
    lastUpdate: number;

    /**
     * Number of measurements obtained during latest update
     */
    totalMeasurementsInLastUpdate: number;

    /**
     * Example: CONNECTED
     */
    connectStatus?: string;

    /**
     * Example: 2017-07-18 05:16:31
     */
    updateRequestedAt?: Date;

    /**
     * Example: Tracks social interaction. QuantiModo requires permission to access your Facebook \"user likes\" and \"user posts\".
     */
    shortDescription?: string;

    /**
     * Example: Got 412 new measurements on 2017-07-31 10:10:34
     */
    message?: string;

    /**
     * Example: 2017-07-31 10:10:34
     */
    lastSuccessfulUpdatedAt?: Date;

    /**
     * Example: <a href=\"http://www.facebook.com\"><img id=\"facebook_image\" title=\"Facebook\" src=\"https://i.imgur.com/GhwqK4f.png\" alt=\"Facebook\"></a>
     */
    imageHtml?: string;

    /**
     * Example: UPDATED
     */
    updateStatus?: string;

    /**
     * Example: {}
     */
    oauth?: any;

    /**
     * Example: Social Interactions
     */
    defaultVariableCategoryName?: string;

    /**
     * Example: 225078261031461
     */
    connectorClientId?: string;

    /**
     * Example: Facebook is a social networking website where users may create a personal profile, add other users as friends, and exchange messages.
     */
    longDescription?: string;

    /**
     * Example: 1
     */
    enabled?: number;

    /**
     * Example: <a href=\"http://www.facebook.com\">Facebook</a>
     */
    linkedDisplayNameHtml?: string;

    /**
     * Example: ghostInspector
     */
    clientId?: string;

    /**
     * Example: 230
     */
    userId?: number;

    /**
     * Example: 8
     */
    connectorId?: number;

    /**
     * Example: 2000-01-01 00:00:00
     */
    createdAt?: Date;

    /**
     * Example: 2017-07-31 10:10:34
     */
    updatedAt?: Date;

}
