/**
 * quantimodo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.728
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ConversionStep {
    /**
     * ADD or MULTIPLY
     */
    operation: ConversionStep.OperationEnum;

    /**
     * This specifies the order of conversion steps starting with 0
     */
    value: number;

}
export namespace ConversionStep {
    export enum OperationEnum {
        MULTIPLY = <any> 'MULTIPLY',
        ADD = <any> 'ADD'
    }
}
