/**
 * quantimodo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.728
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Correlation {
    /**
     * 
     */
    averageDailyLowCause?: number;

    /**
     * 
     */
    averageDailyHighCause?: number;

    /**
     * 
     */
    averageEffect?: number;

    /**
     * 
     */
    averageEffectFollowingHighCause?: number;

    /**
     * 
     */
    averageEffectFollowingLowCause?: number;

    /**
     * 
     */
    averageEffectFollowingHighCauseExplanation?: string;

    /**
     * 
     */
    averageEffectFollowingLowCauseExplanation?: string;

    /**
     * Average Vote
     */
    averageVote?: number;

    /**
     * 
     */
    causalityFactor?: number;

    /**
     * Variable name of the cause variable for which the user desires correlations.
     */
    cause: string;

    /**
     * Variable category of the cause variable.
     */
    causeVariableCategoryName?: string;

    /**
     * Number of changes in the predictor variable (a.k.a the number of experiments)
     */
    causeChanges?: number;

    /**
     * The way cause measurements are aggregated
     */
    causeVariableCombinationOperation?: string;

    /**
     * 
     */
    causeVariableImageUrl?: string;

    /**
     * For use in Ionic apps
     */
    causeVariableIonIcon?: string;

    /**
     * Unit of the predictor variable
     */
    causeUnit?: string;

    /**
     * Unit Id of the predictor variable
     */
    causeVariableDefaultUnitId?: number;

    /**
     * 
     */
    causeVariableId?: number;

    /**
     * Variable name of the cause variable for which the user desires correlations.
     */
    causeVariableName?: string;

    /**
     * Pearson correlation coefficient between cause and effect measurements
     */
    correlationCoefficient: number;

    /**
     * When the record was first created. Use UTC ISO 8601 `YYYY-MM-DDThh:mm:ss`  datetime format
     */
    createdAt?: Date;

    /**
     * How the data was analyzed
     */
    dataAnalysis?: string;

    /**
     * How the data was obtained
     */
    dataSources?: string;

    /**
     * The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.
     */
    durationOfAction: number;

    /**
     * Variable name of the effect variable for which the user desires correlations.
     */
    effect: string;

    /**
     * Variable category of the effect variable.
     */
    effectVariableCategoryName?: string;

    /**
     * 
     */
    effectVariableImageUrl?: string;

    /**
     * For use in Ionic apps
     */
    effectVariableIonIcon?: string;

    /**
     * Magnitude of the effects of a cause indicating whether it's practically meaningful.
     */
    effectSize?: string;

    /**
     * Magnitude of the effects of a cause indicating whether it's practically meaningful.
     */
    effectVariableId?: string;

    /**
     * Variable name of the effect variable for which the user desires correlations.
     */
    effectVariableName?: string;

    /**
     * Illustrates the strength of the relationship
     */
    gaugeImage?: string;

    /**
     * Large image for Facebook
     */
    imageUrl?: string;

    /**
     * Number of points that went into the correlation calculation
     */
    numberOfPairs: number;

    /**
     * The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the onset delay. For example, the onset delay between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes.
     */
    onsetDelay: number;

    /**
     * Optimal Pearson Product
     */
    optimalPearsonProduct?: number;

    /**
     * original name of the cause.
     */
    outcomeDataSources?: string;

    /**
     * HIGHER Remeron predicts HIGHER Overall Mood
     */
    predictorExplanation?: string;

    /**
     * Mike Sinn
     */
    principalInvestigator?: string;

    /**
     * Value representing the significance of the relationship as a function of crowdsourced insights, predictive strength, data quantity, and data quality
     */
    qmScore?: number;

    /**
     * Correlation when cause and effect are reversed. For any causal relationship, the forward correlation should exceed the reverse correlation.
     */
    reverseCorrelation?: number;

    /**
     * Using a two-tailed t-test with alpha = 0.05, it was determined that the change...
     */
    significanceExplanation?: string;

    /**
     * A function of the effect size and sample size
     */
    statisticalSignificance?: string;

    /**
     * weak, moderate, strong
     */
    strengthLevel?: string;

    /**
     * These data suggest with a high degree of confidence...
     */
    studyAbstract?: string;

    /**
     * In order to reduce suffering through the advancement of human knowledge...
     */
    studyBackground?: string;

    /**
     * This study is based on data donated by one QuantiModo user...
     */
    studyDesign?: string;

    /**
     * As with any human experiment, it was impossible to control for all potentially confounding variables...
     */
    studyLimitations?: string;

    /**
     * Url for the interactive study within the web app
     */
    studyLinkDynamic?: string;

    /**
     * Url for sharing the study on Facebook
     */
    studyLinkFacebook?: string;

    /**
     * Url for sharing the study on Google+
     */
    studyLinkGoogle?: string;

    /**
     * Url for sharing the study on Twitter
     */
    studyLinkTwitter?: string;

    /**
     * Url for sharing the statically rendered study on social media
     */
    studyLinkStatic?: string;

    /**
     * The objective of this study is to determine...
     */
    studyObjective?: string;

    /**
     * This analysis suggests that...
     */
    studyResults?: string;

    /**
     * N1 Study HIGHER Remeron predicts HIGHER Overall Mood
     */
    studyTitle?: string;

    /**
     * Time at which correlation was calculated
     */
    timestamp: number;

    /**
     * When the record in the database was last updated. Use UTC ISO 8601 `YYYY-MM-DDThh:mm:ss`  datetime format. Time zone should be UTC and not local.
     */
    updatedAt?: Date;

    /**
     * User Vote
     */
    userVote?: number;

    /**
     * cause value that predicts an above average effect value (in default unit for cause variable)
     */
    valuePredictingHighOutcome?: number;

    /**
     * Overall Mood, on average, 34% HIGHER after around 3.98mg Remeron
     */
    valuePredictingHighOutcomeExplanation?: string;

    /**
     * cause value that predicts a below average effect value (in default unit for cause variable)
     */
    valuePredictingLowOutcome?: number;

    /**
     * Overall Mood, on average, 4% LOWER after around 0mg Remeron
     */
    valuePredictingLowOutcomeExplanation?: string;

    /**
     * Example: 0.396
     */
    averageForwardPearsonCorrelationOverOnsetDelays?: number;

    /**
     * Example: 0.453667
     */
    averageReversePearsonCorrelationOverOnsetDelays?: number;

    /**
     * Example: 0.14344467795996
     */
    confidenceInterval?: number;

    /**
     * Example: 1.646
     */
    criticalTValue?: number;

    /**
     * Example: 193
     */
    effectChanges?: number;

    /**
     * Example: 2014-07-30 12:50:00
     */
    experimentEndTime?: Date;

    /**
     * Example: 2012-05-06 21:15:00
     */
    experimentStartTime?: Date;

    /**
     * Example: 0.528359
     */
    forwardSpearmanCorrelationCoefficient?: number;

    /**
     * Example: -86400
     */
    onsetDelayWithStrongestPearsonCorrelation?: number;

    /**
     * Example: 0.477
     */
    pearsonCorrelationWithNoOnsetDelay?: number;

    /**
     * Example: 0.538
     */
    predictivePearsonCorrelation?: number;

    /**
     * Example: 17
     */
    predictsHighEffectChange?: number;

    /**
     * Example: -11
     */
    predictsLowEffectChange?: number;

    /**
     * Example: 0.613
     */
    strongestPearsonCorrelationCoefficient?: number;

    /**
     * Example: 9.6986079652717
     */
    tValue?: number;

    /**
     * Example: 230
     */
    userId?: number;

    /**
     * Example: 6
     */
    causeVariableMostCommonConnectorId?: number;

    /**
     * Example: 6
     */
    causeVariableCategoryId?: number;

    /**
     * Example: MEAN
     */
    effectVariableCombinationOperation?: string;

    /**
     * Example: Mood_(psychology)
     */
    effectVariableCommonAlias?: string;

    /**
     * Example: 10
     */
    effectVariableDefaultUnitId?: number;

    /**
     * Example: 10
     */
    effectVariableMostCommonConnectorId?: number;

    /**
     * Example: 1
     */
    effectVariableCategoryId?: number;

    /**
     * Example: 1
     */
    causeUserVariableShareUserMeasurements?: number;

    /**
     * Example: 1
     */
    effectUserVariableShareUserMeasurements?: number;

    /**
     * Example: -1
     */
    predictorFillingValue?: number;

    /**
     * Example: -1
     */
    outcomeFillingValue?: number;

    /**
     * Example: 2016-12-28 20:47:30
     */
    createdTime?: Date;

    /**
     * Example: 2017-05-06 15:40:38
     */
    updatedTime?: Date;

    /**
     * Example: 168
     */
    durationOfActionInHours?: number;

    /**
     * Example: -24
     */
    onsetDelayWithStrongestPearsonCorrelationInHours?: number;

    /**
     * Example: higher
     */
    direction?: string;

    /**
     * Example: /5
     */
    causeVariableDefaultUnitAbbreviatedName?: string;

    /**
     * Example: /5
     */
    effectVariableDefaultUnitAbbreviatedName?: string;

    /**
     * Example: 1 to 5 Rating
     */
    causeVariableDefaultUnitName?: string;

    /**
     * Example: 1 to 5 Rating
     */
    effectVariableDefaultUnitName?: string;

    /**
     * Example: 1
     */
    shareUserMeasurements?: boolean;

    /**
     * Example: /5
     */
    effectUnit?: string;

    /**
     * Example: 1
     */
    significantDifference?: boolean;

    /**
     * Example: , on average, 17% 
     */
    predictsHighEffectChangeSentenceFragment?: string;

    /**
     * Example: , on average, 11% 
     */
    predictsLowEffectChangeSentenceFragment?: string;

    /**
     * Example: high
     */
    confidenceLevel?: string;

    /**
     * Example: 0.538
     */
    predictivePearsonCorrelationCoefficient?: number;

    /**
     * Example: mailto:?subject=N1%20Study%3A%20Sleep%20Quality%20Predicts%20Higher%20Overall%20Mood&body=Check%20out%20my%20study%20at%20https%3A%2F%2Flocal.quantimo.do%2Fapi%2Fv2%2Fstudy%3FcauseVariableName%3DSleep%2520Quality%26effectVariableName%3DOverall%2520Mood%26userId%3D230%0A%0AHave%20a%20great%20day!
     */
    studyLinkEmail?: string;

    /**
     * Example: https://s3.amazonaws.com/quantimodo-docs/images/gauge-moderately-positive-relationship-200-200.png
     */
    gaugeImageSquare?: string;

    /**
     * Example: {\"id\":6,\"name\":\"up\",\"connectorClientId\":\"10RfjEgKr8U\",\"connectorClientSecret\":\"e17fd34e4bc4642f0c4c99d7acb6e661\",\"displayName\":\"Up by Jawbone\",\"image\":\"https://i.imgur.com/MXNQy3T.png\",\"getItUrl\":\"http://www.amazon.com/gp/product/B00A17IAO0/ref=as_li_qf_sp_asin_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00A17IAO0&linkCode=as2&tag=quant08-20\",\"shortDescription\":\"Tracks sleep, exercise, and diet.\",\"longDescription\":\"UP by Jawbone is a wristband and app that tracks how you sleep, move and eat and then helps you use that information to feel your best.\",\"enabled\":1,\"affiliate\":true,\"defaultVariableCategoryName\":\"Physical Activity\",\"imageHtml\":\"<a href=\\\"http://www.amazon.com/gp/product/B00A17IAO0/ref=as_li_qf_sp_asin_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00A17IAO0&linkCode=as2&tag=quant08-20\\\"><img id=\\\"up_image\\\" title=\\\"Up by Jawbone\\\" src=\\\"https://i.imgur.com/MXNQy3T.png\\\" alt=\\\"Up by Jawbone\\\"></a>\",\"linkedDisplayNameHtml\":\"<a href=\\\"http://www.amazon.com/gp/product/B00A17IAO0/ref=as_li_qf_sp_asin_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00A17IAO0&linkCode=as2&tag=quant08-20\\\">Up by Jawbone</a>\"}
     */
    causeDataSource?: any;

    /**
     * Example: Sleep Quality data was primarily collected using <a href=\"http://www.amazon.com/gp/product/B00A17IAO0/ref=as_li_qf_sp_asin_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00A17IAO0&linkCode=as2&tag=quant08-20\">Up by Jawbone</a>.  UP by Jawbone is a wristband and app that tracks how you sleep, move and eat and then helps you use that information to feel your best.
     */
    dataSourcesParagraphForCause?: string;

    /**
     * Example: <a href=\"http://www.amazon.com/gp/product/B00A17IAO0/ref=as_li_qf_sp_asin_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00A17IAO0&linkCode=as2&tag=quant08-20\">Obtain Up by Jawbone</a> and use it to record your Sleep Quality. Once you have a <a href=\"http://www.amazon.com/gp/product/B00A17IAO0/ref=as_li_qf_sp_asin_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00A17IAO0&linkCode=as2&tag=quant08-20\">Up by Jawbone</a> account, <a href=\"https://app.quantimo.do/ionic/Modo/www/#/app/import\">connect your  Up by Jawbone account at QuantiModo</a> to automatically import and analyze your data.
     */
    instructionsForCause?: string;

    /**
     * Example: {\"id\":72,\"name\":\"quantimodo\",\"displayName\":\"QuantiModo\",\"image\":\"https://app.quantimo.do/ionic/Modo/www/img/logos/quantimodo-logo-qm-rainbow-200-200.png\",\"getItUrl\":\"https://quantimo.do\",\"shortDescription\":\"Tracks anything\",\"longDescription\":\"QuantiModo is a Chrome extension, Android app, iOS app, and web app that allows you to easily track mood, symptoms, or any outcome you want to optimize in a fraction of a second.  You can also import your data from over 30 other apps and devices like Fitbit, Rescuetime, Jawbone Up, Withings, Facebook, Github, Google Calendar, Runkeeper, MoodPanda, Slice, Google Fit, and more.  QuantiModo then analyzes your data to identify which hidden factors are most likely to be influencing your mood or symptoms and their optimal daily values.\",\"enabled\":0,\"affiliate\":true,\"defaultVariableCategoryName\":\"Foods\",\"imageHtml\":\"<a href=\\\"https://quantimo.do\\\"><img id=\\\"quantimodo_image\\\" title=\\\"QuantiModo\\\" src=\\\"https://app.quantimo.do/ionic/Modo/www/img/logos/quantimodo-logo-qm-rainbow-200-200.png\\\" alt=\\\"QuantiModo\\\"></a>\",\"linkedDisplayNameHtml\":\"<a href=\\\"https://quantimo.do\\\">QuantiModo</a>\"}
     */
    effectDataSource?: any;

    /**
     * Example: Overall Mood data was primarily collected using <a href=\"https://quantimo.do\">QuantiModo</a>.  <a href=\"https://quantimo.do\">QuantiModo</a> is a Chrome extension, Android app, iOS app, and web app that allows you to easily track mood, symptoms, or any outcome you want to optimize in a fraction of a second.  You can also import your data from over 30 other apps and devices like Fitbit, Rescuetime, Jawbone Up, Withings, Facebook, Github, Google Calendar, Runkeeper, MoodPanda, Slice, Google Fit, and more.  <a href=\"https://quantimo.do\">QuantiModo</a> then analyzes your data to identify which hidden factors are most likely to be influencing your mood or symptoms and their optimal daily values.
     */
    dataSourcesParagraphForEffect?: string;

    /**
     * Example: <a href=\"https://quantimo.do\">Obtain QuantiModo</a> and use it to record your Overall Mood. Once you have a <a href=\"https://quantimo.do\">QuantiModo</a> account, <a href=\"https://app.quantimo.do/ionic/Modo/www/#/app/import\">connect your  QuantiModo account at QuantiModo</a> to automatically import and analyze your data.
     */
    instructionsForEffect?: string;

}
