/**
 * quantimodo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.728
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface MeasurementSet {
    /**
     * Array of timestamps, values, and optional notes
     */
    measurementItems: Array<models.MeasurementItem>;

    /**
     * ORIGINAL name of the variable for which we are creating the measurement records
     */
    variableName: string;

    /**
     * Name of the application or device used to record the measurement values
     */
    sourceName: string;

    /**
     * Variable category name
     */
    variableCategoryName?: string;

    /**
     * Way to aggregate measurements over time. Options are \"MEAN\" or \"SUM\". SUM should be used for things like minutes of exercise.  If you use MEAN for exercise, then a person might exercise more minutes in one day but add separate measurements that were smaller.  So when we are doing correlational analysis, we would think that the person exercised less that day even though they exercised more.  Conversely, we must use MEAN for things such as ratings which cannot be SUMMED.
     */
    combinationOperation?: MeasurementSet.CombinationOperationEnum;

    /**
     * Unit of measurement
     */
    unitAbbreviatedName: string;

}
export namespace MeasurementSet {
    export enum CombinationOperationEnum {
        MEAN = <any> 'MEAN',
        SUM = <any> 'SUM'
    }
}
