/**
 * quantimodo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.728
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface MeasurementUpdate {
    /**
     * Variable id of the measurement to be updated
     */
    id: number;

    /**
     * The new timestamp for the the event in epoch seconds (optional)
     */
    startTime?: number;

    /**
     * The new value of for the measurement (optional)
     */
    value?: number;

    /**
     * The new note for the measurement (optional)
     */
    note?: string;

}
