/**
 * quantimodo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.728
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Measurement {
    /**
     * Name of the variable for which we are creating the measurement records
     */
    variableName: string;

    /**
     * Application or device used to record the measurement values
     */
    sourceName: string;

    /**
     * Start Time for the measurement event in UTC ISO 8601 `YYYY-MM-DDThh:mm:ss`
     */
    startTimeString: string;

    /**
     * Seconds between the start of the event measured and 1970 (Unix timestamp)
     */
    startTimeEpoch?: number;

    /**
     * Converted measurement value in requested unit
     */
    value: number;

    /**
     * Original value as originally submitted
     */
    originalValue?: number;

    /**
     * Original Unit of measurement as originally submitted
     */
    originalunitAbbreviatedName?: string;

    /**
     * Abbreviated name for the unit of measurement
     */
    unitAbbreviatedName: string;

    /**
     * Note of measurement
     */
    note?: string;

    /**
     * Example: 23
     */
    unitId?: number;

    /**
     * Example: 5956846
     */
    variableId?: number;

    /**
     * Example: 13
     */
    variableCategoryId?: number;

    /**
     * Example: 23
     */
    userVariableDefaultUnitId?: number;

    /**
     * Example: 1051466127
     */
    id?: number;

    /**
     * Example: 23
     */
    originalUnitId?: number;

    /**
     * Example: quantimodo
     */
    clientId?: string;

    /**
     * Example: 2017-07-30 21:08:36
     */
    createdAt?: string;

    /**
     * Example: 2017-07-30 21:08:36
     */
    updatedAt?: string;

    /**
     * Example: Treatments
     */
    variableCategoryName?: string;

    /**
     * Example: 13
     */
    userVariableVariableCategoryId?: number;

    /**
     * Example: ion-ios-medkit-outline
     */
    ionIcon?: string;

    /**
     * Example: https://app.quantimo.do/ionic/Modo/www/img/variable_categories/treatments.svg
     */
    svgUrl?: string;

    /**
     * Example: https://app.quantimo.do/ionic/Modo/www/img/variable_categories/treatments.png
     */
    pngUrl?: string;

    /**
     * Example: img/variable_categories/treatments.png
     */
    pngPath?: string;

    /**
     * Example: https://maxcdn.icons8.com/Color/PNG/96/Healthcare/pill-96.png
     */
    variableCategoryImageUrl?: string;

    /**
     * Example: 1
     */
    manualTracking?: boolean;

    /**
     * Example: Treatments
     */
    userVariableVariableCategoryName?: string;

    /**
     * Example: {\"date\":\"2017-07-30 20:05:30.000000\",\"timezone_type\":1,\"timezone\":\"+00:00\"}
     */
    humanTime?: any;

    /**
     * Example: Count
     */
    unitName?: string;

    /**
     * Example: 6
     */
    unitCategoryId?: number;

    /**
     * Example: Miscellany
     */
    unitCategoryName?: string;

    /**
     * Example: Count
     */
    userVariableDefaultUnitName?: string;

    /**
     * Example: count
     */
    userVariableDefaultUnitAbbreviatedName?: string;

    /**
     * Example: 6
     */
    userVariableDefaultUnitCategoryId?: number;

    /**
     * Example: Miscellany
     */
    userVariableDefaultUnitCategoryName?: string;

    /**
     * Example: Count
     */
    originalUnitName?: string;

    /**
     * Example: count
     */
    originalUnitAbbreviatedName?: string;

    /**
     * Example: 6
     */
    originalUnitCategoryId?: number;

    /**
     * Example: Miscellany
     */
    originalUnitCategoryName?: string;

    /**
     * Example: value
     */
    inputType?: string;

    /**
     * Example: negative
     */
    variableDescription?: string;

    /**
     * Example: negative
     */
    valence?: string;

    /**
     * Example: ion-sad-outline
     */
    iconIcon?: string;

    /**
     * Example: 1
     */
    minimumAllowedValue?: number;

    /**
     * Example: 5
     */
    maximumAllowedValue?: number;

}
