/**
 * quantimodo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.728
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface TrackingReminderNotificationPost {
    /**
     * Id of the TrackingReminderNotification
     */
    id: number;

    /**
     * Optional value to be recorded instead of the tracking reminder default value
     */
    modifiedValue?: number;

    /**
     * track records a measurement for the notification.  snooze changes the notification to 1 hour from now. skip deletes the notification.
     */
    action: TrackingReminderNotificationPost.ActionEnum;

}
export namespace TrackingReminderNotificationPost {
    export enum ActionEnum {
        Track = <any> 'track',
        Snooze = <any> 'snooze',
        Skip = <any> 'skip'
    }
}
