/**
 * quantimodo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.728
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface TrackingReminder {
    /**
     * id
     */
    id?: number;

    /**
     * clientId
     */
    clientId?: string;

    /**
     * ID of User
     */
    userId?: number;

    /**
     * Id for the variable to be tracked
     */
    variableId: number;

    /**
     * Default value to use for the measurement when tracking
     */
    defaultValue: number;

    /**
     * Earliest time of day at which reminders should appear in UTC HH:MM:SS format
     */
    reminderStartTime?: string;

    /**
     * Latest time of day at which reminders should appear in UTC HH:MM:SS format
     */
    reminderEndTime?: string;

    /**
     * String identifier for the sound to accompany the reminder
     */
    reminderSound?: string;

    /**
     * Number of seconds between one reminder and the next
     */
    reminderFrequency: number;

    /**
     * True if the reminders should appear as a popup notification
     */
    popUp?: boolean;

    /**
     * True if the reminders should be delivered via SMS
     */
    sms?: boolean;

    /**
     * True if the reminders should be delivered via email
     */
    email?: boolean;

    /**
     * True if the reminders should appear in the notification bar
     */
    notificationBar?: boolean;

    /**
     * UTC ISO 8601 `YYYY-MM-DDThh:mm:ss`  timestamp for the reminder time of the latest tracking reminder notification that has been pre-emptively generated in the database
     */
    latestTrackingReminderNotificationReminderTime?: Date;

    /**
     * UTC ISO 8601 `YYYY-MM-DDThh:mm:ss`  timestamp for the last time a measurement was received for this user and variable
     */
    lastTracked?: Date;

    /**
     * Earliest date on which the user should be reminded to track in YYYY-MM-DD format
     */
    startTrackingDate?: string;

    /**
     * Latest date on which the user should be reminded to track in YYYY-MM-DD format
     */
    stopTrackingDate?: string;

    /**
     * When the record in the database was last updated. Use UTC ISO 8601 `YYYY-MM-DDThh:mm:ss`  datetime format. Time zone should be UTC and not local.
     */
    updatedAt?: Date;

    /**
     * Name of the variable to be used when sending measurements
     */
    variableName?: string;

    /**
     * Name of the variable category to be used when sending measurements
     */
    variableCategoryName?: string;

    /**
     * Abbreviated name of the unit to be used when sending measurements
     */
    unitAbbreviatedName?: string;

    /**
     * The way multiple measurements are aggregated over time
     */
    combinationOperation?: TrackingReminder.CombinationOperationEnum;

    /**
     * Example: 2016-05-18 02:24:08
     */
    createdAt?: Date;

    /**
     * Example: 11841
     */
    trackingReminderId?: number;

    /**
     * Example: 10
     */
    defaultUnitId?: number;

    /**
     * Example: negative
     */
    variableDescription?: string;

    /**
     * Example: negative
     */
    valence?: string;

    /**
     * Example: ion-sad-outline
     */
    ionIcon?: string;

    /**
     * Example: 10
     */
    variableCategoryId?: number;

    /**
     * Example: 2
     */
    lastValue?: number;

    /**
     * Example: 1
     */
    secondToLastValue?: number;

    /**
     * Example: 3
     */
    thirdToLastValue?: number;

    /**
     * Example: 10
     */
    userVariableDefaultUnitId?: number;

    /**
     * Example: 10
     */
    userVariableVariableCategoryId?: number;

    /**
     * Example: 445
     */
    numberOfRawMeasurements?: number;

    /**
     * Example: https://app.quantimo.do/ionic/Modo/www/img/variable_categories/symptoms.svg
     */
    svgUrl?: string;

    /**
     * Example: https://app.quantimo.do/ionic/Modo/www/img/variable_categories/symptoms.png
     */
    pngUrl?: string;

    /**
     * Example: img/variable_categories/symptoms.png
     */
    pngPath?: string;

    /**
     * Example: https://maxcdn.icons8.com/Color/PNG/96/Messaging/sad-96.png
     */
    variableCategoryImageUrl?: string;

    /**
     * Example: 1
     */
    manualTracking?: boolean;

    /**
     * Example: Symptoms
     */
    userVariableVariableCategoryName?: string;

    /**
     * Example: 21:45:20
     */
    reminderStartTimeLocal?: Date;

    /**
     * Example: 09:45 PM
     */
    reminderStartTimeLocalHumanFormatted?: Date;

    /**
     * Example: 2
     */
    lastValueInUserVariableDefaultUnit?: number;

    /**
     * Example: 1
     */
    secondToLastValueInUserVariableDefaultUnit?: number;

    /**
     * Example: 3
     */
    thirdToLastValueInUserVariableDefaultUnit?: number;

    /**
     * Example: 10
     */
    unitId?: number;

    /**
     * Example: 1 to 5 Rating
     */
    unitName?: string;

    /**
     * Example: 5
     */
    unitCategoryId?: number;

    /**
     * Example: Rating
     */
    unitCategoryName?: string;

    /**
     * Example: 1 to 5 Rating
     */
    defaultUnitName?: string;

    /**
     * Example: /5
     */
    defaultUnitAbbreviatedName?: string;

    /**
     * Example: 5
     */
    defaultUnitCategoryId?: number;

    /**
     * Example: Rating
     */
    defaultUnitCategoryName?: string;

    /**
     * Example: 1 to 5 Rating
     */
    userVariableDefaultUnitName?: string;

    /**
     * Example: /5
     */
    userVariableDefaultUnitAbbreviatedName?: string;

    /**
     * Example: 5
     */
    userVariableDefaultUnitCategoryId?: number;

    /**
     * Example: Rating
     */
    userVariableDefaultUnitCategoryName?: string;

    /**
     * Example: 1
     */
    minimumAllowedValue?: number;

    /**
     * Example: 5
     */
    maximumAllowedValue?: number;

    /**
     * Example: saddestFaceIsFive
     */
    inputType?: string;

    /**
     * Example: 1469760320
     */
    reminderStartEpochSeconds?: number;

    /**
     * Example: 1501555520
     */
    nextReminderTimeEpochSeconds?: number;

    /**
     * Example: 02:45:20
     */
    firstDailyReminderTime?: Date;

    /**
     * Example: Daily
     */
    frequencyTextDescription?: string;

    /**
     * Example: Daily at 09:45 PM
     */
    frequencyTextDescriptionWithTime?: string;

    /**
     * Example: Rate daily
     */
    valueAndFrequencyTextDescription?: string;

    /**
     * Example: Rate daily at 09:45 PM
     */
    valueAndFrequencyTextDescriptionWithTime?: string;

}
export namespace TrackingReminder {
    export enum CombinationOperationEnum {
        MEAN = <any> 'MEAN',
        SUM = <any> 'SUM'
    }
}
