/**
 * quantimodo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.728
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Unit {
    /**
     * Unit name
     */
    name: string;

    /**
     * Unit abbreviation
     */
    abbreviatedName: string;

    /**
     * Unit category
     */
    category: Unit.CategoryEnum;

    /**
     * The minimum allowed value for measurements. While you can record a value below this minimum, it will be excluded from the correlation analysis.
     */
    minimumAllowedValue?: number;

    /**
     * The maximum allowed value for measurements. While you can record a value above this maximum, it will be excluded from the correlation analysis.
     */
    maximumAllowedValue?: number;

    /**
     * Conversion steps list
     */
    conversionSteps: Array<models.ConversionStep>;

    /**
     * Example: 29
     */
    id?: number;

    /**
     * Example: Miscellany
     */
    categoryName?: string;

    /**
     * Example: 6
     */
    categoryId?: number;

    /**
     * Example: 1
     */
    advanced?: number;

}
export namespace Unit {
    export enum CategoryEnum {
        Distance = <any> 'Distance',
        Duration = <any> 'Duration',
        Energy = <any> 'Energy',
        Frequency = <any> 'Frequency',
        Miscellany = <any> 'Miscellany',
        Pressure = <any> 'Pressure',
        Proportion = <any> 'Proportion',
        Rating = <any> 'Rating',
        Temperature = <any> 'Temperature',
        Volume = <any> 'Volume',
        Weight = <any> 'Weight'
    }
}
