/**
 * quantimodo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.728
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Vote {
    /**
     * id
     */
    id?: number;

    /**
     * clientId
     */
    clientId: string;

    /**
     * ID of User
     */
    userId: number;

    /**
     * Cause variable id
     */
    causeVariableId: number;

    /**
     * Effect variable id
     */
    effectVariableId: number;

    /**
     * Vote: 0 (for implausible) or 1 (for plausible)
     */
    value: boolean;

    /**
     * When the record was first created. Use UTC ISO 8601 `YYYY-MM-DDThh:mm:ss`  datetime format
     */
    createdAt?: Date;

    /**
     * When the record in the database was last updated. Use UTC ISO 8601 `YYYY-MM-DDThh:mm:ss`  datetime format
     */
    updatedAt?: Date;

}
