/**
 * QuantiModo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface UserVariableRelationship {
    /**
     * id
     */
    id?: number;

    /**
     * Our confidence that a consistent predictive relationship exists based on the amount of evidence, reproducibility, and other factors
     */
    confidenceLevel: string;

    /**
     * A quantitative representation of our confidence that a consistent predictive relationship exists based on the amount of evidence, reproducibility, and other factors
     */
    confidenceScore: number;

    /**
     * Direction is positive if higher predictor values generally precede higher outcome values. Direction is negative if higher predictor values generally precede lower outcome values.
     */
    direction: string;

    /**
     * The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.
     */
    durationOfAction: number;

    /**
     * error_message
     */
    errorMessage?: string;

    /**
     * The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes.
     */
    onsetDelay?: number;

    /**
     * Variable ID for the outcome variable
     */
    outcomeVariableId: number;

    /**
     * Variable ID for the predictor variable
     */
    predictorVariableId: number;

    /**
     * ID for default unit of the predictor variable
     */
    predictorUnitId: number;

    /**
     * A value representative of the relevance of this predictor relative to other predictors of this outcome.  Usually used for relevancy sorting.
     */
    sinnRank: number;

    /**
     * Can be weak, medium, or strong based on the size of the effect which the predictor appears to have on the outcome relative to other variable relationship strength scores.
     */
    strengthLevel: string;

    /**
     * A value represented to the size of the effect which the predictor appears to have on the outcome.
     */
    strengthScore: number;

    /**
     * userId
     */
    userId?: number;

    /**
     * vote
     */
    vote?: string;

    /**
     * Value for the predictor variable (in it's default unit) which typically precedes an above average outcome value
     */
    valuePredictingHighOutcome: number;

    /**
     * Value for the predictor variable (in it's default unit) which typically precedes a below average outcome value
     */
    valuePredictingLowOutcome: number;

}
